### ISSUE TITLE
ED Discovery Hanging / Not reading in all Flight Logs

### ISSUE THREAD

**Issue by Clampitts** [EDDiscovery/EDDiscovery-Mac#2]
Worked great - now having a couple of issues

I have it installed on 2 Mac. On my main game machine I have it set to read my log files and also have the API key set. The App hangs when parsing the EDSM files / Log files (it appears)
<img width="1075" alt="screen shot 2016-05-27 at 07 19 48" src="https://cloud.githubusercontent.com/assets/19603917/15600443/bf1b6212-23e1-11e6-9293-722c8ec14fd3.png">
<img width="1115" alt="screen shot 2016-05-27 at 07 15 28" src="https://cloud.githubusercontent.com/assets/19603917/15600442/bf17a028-23e1-11e6-80fe-4a7db4d6cae9.png">

The second installation does not have log file pasring set up as it's not on my Gaming iMac, just the API key. But this does not read EDSM entries before 26/1/16 - even though I have EDSM Flight logs back to Aug 2015. Of note, the files from 26/1/16 (that it is reading) wereuploaded to EDSM before ED 2.1. The files from Aug to Jan were uploaded to ED after / during ED 2.1 rollout. The screen grab below is from non-gaming Mac (without API), parses ok, doesn't have log file installation, but doesn't read all of EDSM flight logs
<img width="1077" alt="screen shot 2016-05-27 at 07 55 08" src="https://cloud.githubusercontent.com/assets/19603917/15600446/c5c1ad1a-23e1-11e6-912d-489d9a92e8d2.png">

**Comment by AnthorNet** [comment]
The error I see means that there is a submission ongoing and that the entry was already found.
Not really an error, just means that the flight logs is already there.

Don't know about your specific issue about why it does not finish the sync :)

**Comment by Clampitts** [comment]
The issue is that the installation that reads the Log files hangs and does not respond.  I had dragged the installation to the 'trash' - re-intsalled with the intent NOT to set up log file parsing, but the new (V1.4) installation read in my preferences.  Can yoiu let me know what to remove from Mac (preferences file) then I'll reinstall and not set up log files?  
That is, I'd reinstall with just the API key?
As soon as I start the main installation, it begins to read EDSM - hangs and I cannot amend the preferences / set up to remove Log file parsing...

**Comment by noberasco** [comment]
To wipe up EDDiscovery data and force it to start from scratch, open up Terminal and delete folder $HOME/Library/Application Support/EDDiscovery

Make sure that EDDiscovery is NOT running when you do this

**Comment by noberasco** [comment]
However, I would like to address your issues ;-)

[First issue (EDDiscovery hanging)]

I see you posted two screenshots: the first one with the 'operation in progress' bar visible, the second one without. Is the application still unresponsive after the progress bar goes away?

The messages highlighted in read are harmless per-se: it is just EDDiscovery warning you about an inconsistency it detected between what it read from the netlog files and what it received from EDSM.

[Second issue (incomplete travel history read from EDSM)]

The second issue could be EDSM not sending me your complete travel history when I ask for it. I can investigate the issue, but I need you to provide me your account credentials for EDSM. On my part, I promise to use the credentials only for the scope of solving this bug, and not to alter your travel history on EDSM in any way.

**Comment by Clampitts** [comment]
Ok, if I do not enter my Log File directory (as I inferred), then a clean installation works.  Means (atm) I can use ED Market Connector (which is nerf'd post 2.1), to upload Log Files to EDSM, or manually drag and drop.  Also, the clean installation on both machines seems to read entire EDSM flight logs - every flight log back to Aug 2015 (~6500)

Interestingly, on the clean install, I just entered my Cmdr name and the API key was auto-populated..

![screen shot 2016-05-27 at 08 43 02](https://cloud.githubusercontent.com/assets/19603917/15601507/a38f0250-23e7-11e6-877c-c9ca79f1153d.png)

IN response to your comment, the application remains 'hung' after the progress bar goes away....

**Comment by noberasco** [comment]
The instructions I sent you cause the application data base to be deleted.
The API key for your commander is stored securely within the Mac KeyChain and is thus unaffected by you touching the data base.

**Comment by noberasco** [comment]
As an experiment: what happens if you make EDDiscovery parse your netlog files AFTER you successfully synced your EDSM account?

**Comment by Clampitts** [comment]
Just going to try that now, I've made a cpl more jumps....

**Comment by Clampitts** [comment]
Ok, ran ok initially (grabs 1 & 2), reopened - then hung (grab 4)

Note that I'd just tried it on my non-NetLog spare Mac Book Pro (Grab 3) and that did not refresh the full jumps (Only 6567, not 7349, which it appears I've made !)
<img width="1169" alt="screen shot 2016-05-27 at 09 09 50" src="https://cloud.githubusercontent.com/assets/19603917/15602298/5b1ee7ce-23ec-11e6-82b8-e5e3d00f950c.png">
<img width="1110" alt="screen shot 2016-05-27 at 09 11 58" src="https://cloud.githubusercontent.com/assets/19603917/15602299/5b1f4f5c-23ec-11e6-8dc2-30720ee38530.png">

<img width="1256" alt="screen shot 2016-05-27 at 09 17 56" src="https://cloud.githubusercontent.com/assets/19603917/15602317/78f213ca-23ec-11e6-8c60-8ff4ffeeddd4.png">

<img width="1031" alt="screen shot 2016-05-27 at 09 14 01" src="https://cloud.githubusercontent.com/assets/19603917/15602313/74d20ae8-23ec-11e6-9f6a-9299f8eeb3a9.png">

**Comment by Clampitts** [comment]
Ok, manually uploaded log file to EDSM and re-run your App, without Log Files - the app on both macs read the same.  So, one with ED installed seems to hang if log file parsing on.  And the other only udpates if netLog files are manually dragged to EDSM (maybe then ED Market Connector is fixed, your NetLog parsing can become redundant, as that sends netLogs to EDSM?)
<img width="1093" alt="screen shot 2016-05-27 at 09 29 54" src="https://cloud.githubusercontent.com/assets/19603917/15602578/f1f613ce-23ed-11e6-8d2d-2c4a325e73c7.png">
<img width="1255" alt="screen shot 2016-05-27 at 09 29 14" src="https://cloud.githubusercontent.com/assets/19603917/15602579/f1f72d72-23ed-11e6-8535-55e62a47d794.png">

**Comment by noberasco** [comment]
My app syncs jumps between netlog files and EDSM.

On normal use (thus after initial sync, which is where you are having issues) it monitors for changes to the netlog files and adds new jumps to your travel history in real time (and sends them to EDSM if you have it configured).

**Comment by noberasco** [comment]
To to the root cause of the app hanging when parsing netlog files, can I have access to them? If you upload them somewhere (e.g.: Dropbox), I'll attempt to reproduce your issues and see what is causing them.

In order to test under your same conditions, I need:
- your complete set of netlog files
- access credentials for your EDSM account

You can e-mail me the details at michele.noberasco AT tiscali DOT it so that they are not publicly shared here.

**Comment by Clampitts** [comment]
I have ~ 800 Netlog files, you want them all!!!

Without setting Log Parsing - and manually uploading netlog files to EDSM, your EDD App updates correctly when opened.  There's no 'refresh' option I see to 'pull' data from EDSM?

**Comment by noberasco** [comment]
I need the files whose name starts with 'netLog.'
And yes, I do know that is a lot of files :-(
The idea is being able to reproduce your exact operating environment...

**Comment by Clampitts** [comment]
Ok, ~390 MByte of netLogs added to dropbox, access credentials for EDSM and Password via email.
I'll add you to Dropbox now

**Comment by Clampitts** [comment]
Is it Tiscali DOT com ?

**Comment by noberasco** [comment]
no, DOT it (I live in Italy)

**Comment by Clampitts** [comment]
Dropbox invite sent

In terms of EDSM, what credentials do you need,

**Comment by noberasco** [comment]
Got it, downloading the files now (it will take a while, I'm on a slow connection).
If my download speed keeps up, tonight I'll have a proper look at the data.

Note that I haven't received your credentials for EDSM, yet.

**Comment by Clampitts** [comment]
Thanks. as above, what credentials do you need???

**Comment by noberasco** [comment]
your username and password for http://edsm.net

**Comment by Clampitts** [comment]
Ok, my Cmdr Name or email??? as well as password

**Comment by noberasco** [comment]
whatever is necessary for you to successfully log in at https://www.edsm.net/login

**Comment by Clampitts** [comment]
Email sent...

**Comment by noberasco** [comment]
E-mail received!

Thank you very much for your cooperation. Tonight do some proper tests to understand why EDDiscovery is mis-behaving with your data.

I'll let you know as soon as I have some results!

**Comment by noberasco** [comment]
Hi there,

some early news. From what I could see, if you use either EDSM or netlog files to populate your travel history (not both), the application seems to work just fine.

However, in the moment you set up both EDDiscovery attempts to sync the two, determines that there is a significant number of jumps from your netlog files that have not yet been sent to EDSM, then chokes on the number of network connections it attempts to create.

So the good news is: apparently I managed to reproduce your problem ;-)

Now I just have to fix it!
Stay tuned :-)

**Comment by Clampitts** [comment]
I'm tuned...

**Comment by Clampitts** [comment]
Y

**Comment by Clampitts** [comment]
Top tastic !!

**Comment by noberasco** [comment]
Second progress update: I found and fixed the bug that caused the application to choke on your data and become unresponsive.

However, your data on netlog / EDSM is so marvelously intricate (I suppose you used a combination of different programs to send netlog files to EDSM over the time) that I discovered a few other issues, which I'm working on.

**Comment by noberasco** [comment]
New status update: bugs apparently fixed, doing test runs.

**Comment by noberasco** [comment]
New status update: most issues fixed, there is a (less severe) leftover one related to UI updating during mass export of jumps to EDSM

**Comment by noberasco** [comment]
All bugs fixed! Doing some final testing, then releasing app update!

**Comment by noberasco** [comment]
Version 1.5 should fix your issues.

Thank you for giving me access to your netlog files and EDSM jumps: these proved invaluable to reproduce and fix a number of issues that I would never have been to reproduce on my own :-)

Unless you report further issues, I will now no longer access your CMDR data...

To summarize:
- incorrect number of jumps downloaded from EDSM: bogus issue, app was downloading the full jump history but reported only the number of new jumps added to the local DB (many jumps had already been parsed from netlog files)
- app becoming unresponsive after parsing netlog files AND downloading jumps from EDSM: multiple issues fixed, should work as expected now
