### ISSUE TITLE
Interrupted systems updates don't get retried

### ISSUE THREAD

**Issue by travellingkiwi** [EDDiscovery/EDDiscovery-Mac#5]
If you interrupt a system update, then the next run will not re-download the updates that were not made. They're lost until you delete the database and start again from scratch.

**Comment by noberasco** [comment]
Bug reproduced and acknowledged.
Will try to fix it and release an update...

**Comment by noberasco** [comment]
@travellingkiwi, yet another commit for you to test ;-)

**Comment by noberasco** [comment]
Hopefully resolved with 426b0e615d9e3c373d00923e92d0e24c475f5cac
