### ISSUE TITLE
Application not running

### ISSUE THREAD

**Issue by Clampitts** [EDDiscovery/EDDiscovery-Mac#9]
App downloaded, cannot get to run!

Version 1.10 was fine - after ED updates, I'll restart Mac...

<img width="538" alt="screen shot 2016-09-20 at 19 34 04" src="https://cloud.githubusercontent.com/assets/19603917/18683704/3c08403c-7f69-11e6-8fc2-ab12f4472a13.png">

**Comment by noberasco** [comment]
What happens exactly when you try to run it?

**Comment by Clampitts** [comment]
Nothing….

Will reboot mac later

[cid:image001.png@01D2138D.5A1CD080]
Tim Arnold | Risktec Solutions Ltd | Wilderspool Park | Greenall's Avenue | Warrington | WA4 6HL | UK
Tel: +44 (0)1925 611200 | Direct: +44 (0)1925 611 217
websitehttp://www.risktec.co.uk/ | consultinghttp://www.risktec.co.uk/consulting.aspx | training & educationhttp://www.risktec.co.uk/training-and-education.aspx | resource solutionshttp://www.risktec.co.uk/resource-solutions.aspx

**Comment by Clampitts** [comment]
Fails to even start on my iMac or MacBook Pro …

[http://www.risktec.co.uk/Images/RisktecLogo.png]
Tim Arnold | Risktec Solutions Ltd | Wilderspool Park | Greenall's Avenue | Warrington | WA4 6HL | UK
Tel: +44 (0)1925 611200 | Direct: +44 (0)1925 611 217
websitehttp://www.risktec.co.uk/ | consultinghttp://www.risktec.co.uk/consulting.aspx | training & educationhttp://www.risktec.co.uk/training-and-education.aspx | resource solutionshttp://www.risktec.co.uk/resource-solutions.aspx

**Comment by gregmcdougall** [comment]
Crashing on start-up.

EXC_CRASH (Code Signature Invalid)

[EDDiscovery_2016-09-20-225959_Gregs-iMac.crash.zip](https://github.com/EDDiscovery/EDDiscovery-Mac/files/483688/EDDiscovery_2016-09-20-225959_Gregs-iMac.crash.zip)

**Comment by noberasco** [comment]
It seems updating to the latest version of Apple developer tools borked app signing for other users but not for me (I can run the app just fine) :-/

Let me see what I can do about this...

**Comment by noberasco** [comment]
Apparently using the new Xcode it is no longer possible to sign mac apps for distribution without paying for an Apple developer membership?!?!? No way I'm paying Apple €99 per year to distribute a free application!

Restoring old version of Xcode from backup, let's see if I can still sign the app using the previous version.

**Comment by noberasco** [comment]
OK, compiling the app with the previous version of Xcode seems to solve the signing issues. I'll release another update after lunch

**Comment by noberasco** [comment]
Hopefully fixed with version 1.12 (51529be1de9820d9298565e245e1c2067edee748)

**Comment by Clampitts** [comment]
Will test later

**Comment by Clampitts** [comment]
Seems to function
[cid:B437B3E3-218A-4C6F-A8F4-8ABAD9105684]

[http://www.risktec.co.uk/Images/RisktecLogo.png]
Tim Arnold | Risktec Solutions Ltd | Wilderspool Park | Greenall's Avenue | Warrington | WA4 6HL | UK
Tel: +44 (0)1925 611200 | Direct: +44 (0)1925 611 217
websitehttp://www.risktec.co.uk/ | consultinghttp://www.risktec.co.uk/consulting.aspx | training & educationhttp://www.risktec.co.uk/training-and-education.aspx | resource solutionshttp://www.risktec.co.uk/resource-solutions.aspx
